# Generated by Django 3.2.7 on 2021-10-01 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedQuote',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('tweet', models.CharField(max_length=240)),
                ('font', models.CharField(max_length=100)),
                ('picture_url', models.CharField(max_length=2048)),
            ],
        ),
    ]
